services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: lc-exchanger-api
    expose:
      - "8080"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: lc-exchanger-client
    depends_on:
      - api
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
